// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_delete from "./routes/api/delete.ts";
import * as $api_get from "./routes/api/get.ts";
import * as $api_isdone from "./routes/api/isdone.ts";
import * as $api_post from "./routes/api/post.ts";
import * as $index from "./routes/index.tsx";
import * as $Box from "./islands/Box.tsx";
import * as $Item from "./islands/Item.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/delete.ts": $api_delete,
    "./routes/api/get.ts": $api_get,
    "./routes/api/isdone.ts": $api_isdone,
    "./routes/api/post.ts": $api_post,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Box.tsx": $Box,
    "./islands/Item.tsx": $Item,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
